ALTER TABLE public."vouchers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."site_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."boosting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."boosting_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."rent_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."wheel_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."deposit_requests" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Auth Manage Vouchers" ON public."vouchers" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Public Select Vouchers" ON public."vouchers" FOR SELECT TO public USING (true);
CREATE POLICY "Auth Transactions" ON public."transactions" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Auth Update Stats" ON public."site_stats" FOR ALL TO public USING (true);
CREATE POLICY "Public Select Stats" ON public."site_stats" FOR SELECT TO public USING (true);
CREATE POLICY "Auth Messages" ON public."messages" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Auth Manage Boost" ON public."boosting" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Public Select Boosting" ON public."boosting" FOR SELECT TO public USING (true);
CREATE POLICY "Auth Manage Accounts" ON public."accounts" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Public Select Accounts" ON public."accounts" FOR SELECT TO public USING (true);
CREATE POLICY "Auth Boosting Req" ON public."boosting_requests" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Auth Rent" ON public."rent_requests" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Auth Users Table" ON public."users" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Enable insert for all users" ON public."users" FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable read access for all users" ON public."users" FOR SELECT TO public USING (true);
CREATE POLICY "Auth Manage Wheel" ON public."wheel_items" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "Public Select Wheel" ON public."wheel_items" FOR SELECT TO public USING (true);
CREATE POLICY "Auth Deposit" ON public."deposit_requests" FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
